apiVersion: v1
kind: Namespace
metadata:
  name: gitops-control-plane
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: agent-managed
  labels:
    argocd.argoproj.io/managed-by: gitops-control-plane
---
apiVersion: v1
kind: Namespace
metadata:
  name: agent-autonomous
  labels:
    argocd.argoproj.io/managed-by: gitops-control-plane
