apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: managed-cluster
  labels:
    argocd.argoproj.io/managed-by: argocd
