apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster2-agent
  namespace: argocd
spec:
  secretName: cluster2-agent
  issuerRef:
    name: argocd-agent-ca
    kind: Issuer
  commonName: cluster2
  dnsNames:
    - cluster2.argocd-agent.local
