apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issuer-argocd-agent-ca.yaml
  # certificate-principal-tls : générer avec envsubst depuis certificate-principal-tls.yaml.template puis oc apply -f -
  - certificate-resource-proxy-tls.yaml
  - certificate-managed-cluster-principal.yaml
  - certificate-managed-cluster-agent.yaml
  - certificate-autonomous-cluster-principal.yaml
  - certificate-autonomous-cluster-agent.yaml
